# Generated by Django 4.2.1 on 2023-09-11 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_domains_domain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='user',
        ),
    ]
