# Generated by Django 4.2.1 on 2023-10-03 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_domain_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Domain',
        ),
    ]
