# Generated by Django 4.2.1 on 2023-10-17 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Community',
            new_name='CommunityDomain',
        ),
        migrations.RenameModel(
            old_name='Drywall',
            new_name='DrywallDomain',
        ),
        migrations.RenameModel(
            old_name='Family',
            new_name='FamilyDomain',
        ),
        migrations.RenameModel(
            old_name='Other',
            new_name='OtherDomain',
        ),
    ]
