# Generated by Django 4.2.1 on 2024-03-02 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0002_rename_community_communitydomain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitydomain',
            name='registrar',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='drywalldomain',
            name='registrar',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='familydomain',
            name='registrar',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='otherdomain',
            name='registrar',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
